nlweb-ai/NLWeb

- README.md
> Revert "Added a wall of contributors"

- code/requirements.txt
updateing requirements for new gemini SDK and constraining two packages (packages and protobuf)
> update requirements to constrain/manage dependency conflicts

- docs/life-of-a-chat-query.md
> Update life-of-a-chat-query.md, small typo

- code/benchmark/run_speed_benchmark.py
- code/retrieval/azure_search_client.py
- code/retrieval/milvus_client.py
- code/retrieval/qdrant.py
- code/retrieval/retriever.py
- code/retrieval/snowflake_client.py
- code/snowflake-connectivity.py
- code/utils/snowflake.sql
Since there were some problems with github with that PR, submitted the same code in a new PR.
> Add changes from PR 150

- README.md
README change only.  Low risk and good for morale.
> Created a contributor wall of fame to encourage contributions

- code/pre_retrieval/decontextualize.py
- static/chat-interface.js
Couple of small unrelated fixes
> Couple of small fixes

- code/.env.template
- code/config/config.py
- code/config/config_retrieval.yaml
- code/retrieval/opensearch_client.py
- code/retrieval/retriever.py
Make it possible to interface with any vector store that provides open search api
> Add open search as a backend

- .gitignore
- code/config/config_retrieval.yaml
- code/scraping/IncrementalReadme.md
- code/scraping/README.md
- code/scraping/__init__.py
- code/scraping/crawlAndLoadSite.py
- code/scraping/embedding.py
- code/scraping/example_usage.py
- code/scraping/expBackOffCrawl.py
- code/scraping/extractMarkup.py
- code/scraping/incrementalCrawlAndLoad.py
- code/scraping/markupFromSite.py
- code/scraping/test_scraping.py
- code/scraping/urlsFromSitemap.py
Read the sitemps to get the URLs, get the site content, extract the markup, compute embeddings, load into db
> Basic scraper

- code/retrieval/azure_search_client.py
- code/tools/db_load_utils.py
- code/tools/parallel_db_load.sh
- code/tools/trim_schema_json.py
> Improvements in data loading

- .gitignore
- code/config/config.py
- code/config/config_retrieval.yaml
- code/core/compare_items.py
- code/core/generate_answer.py
- code/core/item_details.py
- code/core/ranking.py
- code/pre_retrieval/decontextualize.py
- code/retrieval/retriever.py
- code/testing/query_test_runner.py
- code/testing/test_endpoint_results.py
- code/testing/test_queries_and_rss.py
- code/testing/test_retrieval_with_endpoint_stats.py
- code/testing/test_with_clean_db.py
- code/utils/json_utils.py
- docs/retrieval-config.md
Multiple retrieval backends can be enabled at the same time. Queries are sent to all of them and results are merged. Write is still to a single preferred backend.
> Enable Querying from multiple database backends

- code/tools/npr_podcast_scraper_complete.py
- code/tools/process_npr_rss_by_org.py
> Collect NPR Podcasts

- code/config/config_retrieval.yaml
- code/core/baseHandler.py
- code/core/compare_items.py
- code/core/item_details.py
- code/core/router.py
- code/pre_retrieval/decontextualize.py
- code/prompts/site_type.xml
- static/chat-interface.js
- static/managed-event-source.js
Improve decontextualization by passing along previous results as part of the request.
> Improve decontextualization

- static/json-renderer.js
- static/managed-event-source.js
- static/streaming.js
> fix item details UI

- code/core/baseHandler.py
- code/core/ensemble_tool.py
- code/core/router.py
- code/core/test_tools.xml
- code/llm/llm.py
- ensemble_test_queries.md
- static/managed-event-source.js
First pass at ensemble tool.
Also make it so that tools can be loaded on demand. If a tool is enabled and the execution file is found, it will imported and used. No other files have to be changed.
> First pass at ensemble tool

- code/python/core/config.py
added vector_type back to config post-refactoring
> updating elastic config

- Dockerfile
- docker-compose.yaml
After recent code refactoring, Docker configuration files contain incorrect paths that prevent the application from running properly. The refactoring moved Python files into a `python/` subdirectory, but the Docker configurations were not updated accordingly.
This PR fixes critical path issues in Docker configuration files:
- Updated `requirements.txt` path from `code/requirements.txt` to `code/python/requirements.txt`
- Updated CMD entry point from `app-file.py` to `python/app-file.py`
- Fixed volume mount for data directory: `./data:/app/data` (added `/app` prefix)
- Updated config volume mount from `./code/config` to `./config`
- Added missing `NLWEB_CONFIG_DIR` environment variable pointing to `/app/config`
- Built Docker image successfully with `docker build -t nlweb .`
- Verified …
> critical paths fix after code refactoring

- code/python/webserver/mcp_wrapper.py
- static/mcp_test.html
Fixes MCP requests from MCP Test Interface both for Standard and Stream requests.
**CURRENT**
**FIXED**
> fix: mcp test interface both standard and stream request

- .github/workflows/codeql.yaml
This specialized GitHub Actions workflow provides **automated security scanning for fork-based pull requests** using GitHub's CodeQL analysis engine.
- **Runs CodeQL analysis exclusively for PRs from forks** targeting the `main` branch
- **Complements** the repository's built-in CodeQL scanning (no duplicate analysis)
- **Ensures security checks run** even on contributions from external repositories
✅ **Fork-focused**: Only activates for pull requests from forked repositories
✅ **Zero duplication**: Avoids running when repository-level CodeQL is already active
✅ **Same standards**: Applies identical security scanning to external contributions
✅ **Comprehensive**: Includes both security and quality analysis queries
- Uses `pull_request_target` to safely run workflow with repository …
> CodeQL Fork Analysis Workflow

- README.md
Added Postgres to the intro markdown on the home page of the repo.
> Update README.md to add Postgres

- CLAUDE.md
- codingrules.md
- systemmap.md
- test_oauth_config.py
- userworkflow.md
Overview files for claude code
> Overview files
